### ISSUE TITLE
F-Droid

### ISSUE THREAD

**Issue by linsui** [zhaoweihaoChina/MrTranslator#2]
请问是否可以发布到 F-Droid？

**Comment by zhaoweih** [comment]
这个仓库已经很久没有维护了，不知道会不会有什么问题，而且api-key是免费版的，建议更改api-key后发布，如果你需要发布而且是非商业用途可以，请标注我的名字就行。

**Comment by linsui** [comment]
如果不打算继续维护了，那我还是放弃吧。毕竟依赖于有道，随时可能失效。感谢回复！
